services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - weather_network


  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontendservice
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - weather_network
    # другие параметры

networks:
  weather_network:
    driver: bridge